<?php
	
	
	namespace app\widgets;
	
	
	use yii\base\Widget;
	
	class MyWidget
		extends Widget
	{
		
		public $name;
		
		public function init()
		{
			parent::init(); // TODO: Change the autogenerated stub
			if ($this->name === null){
				$this->name = 'Guest';
			}
		}
		
		public function run()
		{
			return "<h1>Hi, {$this->name}</h1>";
		}
	}